### ISSUE TITLE
SapperJs with amazing Poi

### ISSUE THREAD

**Issue by ansarizafar** [egoist/poi#348]
Is it possible to use SapperJs https://sapper.svelte.technology/ with amazing Poi.

**Comment by mblarsen** [comment]
It seems sapper provides all you need to develop so you wouldn't really need poi. Maybe I'm missing something :)

poi has a [svelte preset](https://github.com/egoist/poi/tree/master/packages/poi-preset-svelte) that would provide you with similar functionality. So I guess you could clone the example and with a bit of cleanup you could use poi instead of the sapper webpack setup and such.

Did you have anything in mind?

**Comment by ansarizafar** [comment]
Vue cli/templates also provide all you need to develop but Still, poi has builtin support for Vue. What poi provides is convenience.

**Comment by mblarsen** [comment]
As far as I've understood SapperJs it is a boilerplate for Svelte apps. Poi doesn't do boilerplates. 

You can use [SAO](https://github.com/saojs/sao) (by the same dev as poi) for that. 

Poi provides svelte support through the [svelte preset](https://github.com/egoist/poi/tree/master/packages/poi-preset-svelte).

If I am missing the point please disregard my words :)

**Comment by egoist** [comment]
Using Poi to replace the Sapper CLI seems a bit unnecessary (it's possible though, with a Poi plugin), but you can use Poi to manage your webpack.config.js in a Sapper app if you want. `poi/webpack.config.js` exported the raw webpack config.
