### ISSUE TITLE
Example using background image in CSS

### ISSUE THREAD

**Issue by willmendesneto** [egoist/poi#380]
**Do you want to request a *feature* or report a *bug*?**

Docs improvement

**What is the current behavior?**

There's nothing in the docs or any example covering this case. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

A project inside `examples` folder explaining how to use background image in CSS files with POI.JS

**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

**Comment by KirkOlson** [comment]
I second that

**Comment by allenfantasy** [comment]
+1. Actually after reading the docs and source code I could not find a way to customize the configuration of `ExtractTextPlugin` since I would like to make some CSS background images work. See [this similar issue](https://github.com/vuejs/vue-loader/issues/481#issuecomment-306202382) whose final solution was to change the configuration of `ExtractTextPlugin`.
