### ISSUE TITLE
Missing CLI option: --env.NODE_ENV xxx

### ISSUE THREAD

**Issue by chanjsq** [egoist/poi#458]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Set `process.env.NODE_ENV` to `development`.
**If the current behavior is a bug, please provide the steps to reproduce.**
Run `poi --env.NODE_ENV local`.

**What is the expected behavior?**
Set `process.env.NODE_ENV` to `local`.
**If this is a feature request, what is the motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**
Node.js: 10.5.0
Poi: 10.2.9
OS: macOS 10.13.5

**Comment by k1r0s** [comment]
I was going to ask pretty much same question: 

Dynamically define env values depending on poi [, build] 

So, when I run __poi entry__ some global variable becomes "development" or something
So, when I run __poi build entry__ some global variable becomes "production" or something

Thanks!

**Comment by AndrewDubya** [comment]
I would also like to dynamically define environment variables.

For my app, I need one build that uses indexedDB, and another that uses an API. My code is able to switch between the two, but I need to configure it based on some variable, eg:
poi --env.BACKEND api|idb

The only way I can see to do this would be to have a dev env with indexedDB, and production with the API, which is not what I'm looking for.

**Comment by AndrewDubya** [comment]
I added some code to specify --vars.X="val" on the cli. It seems to work with --vars.NODE_ENV="local" or anything you throw at it. I didn't use --env.X because it seemed like it would clobber the current --env functionality.

This is probably not the way it should be implemented. Around line 76 of node_modules/poi/lib/index.js, I modified the code to:

    this.env = {
      NODE_ENV: process.env.NODE_ENV,
      // Added this to merge vars flags.
      ...options.flags.vars
    }
    if (this.options.env !== false) {
      // Added the line below as well as it overwrites vars.
      Object.assign(this.env, loadEnv(process.env.NODE_ENV), options.flags.vars);
    }

This was enough to give me conditional code execution. I'm not 100% sure if it is hooked in the right place to do what you guys need for NODE_ENV.
