### ISSUE TITLE
POI v12 plugins configuration

### ISSUE THREAD

**Issue by throrin19** [egoist/poi#507]
Hello,

I have questions for specific plugins : 

- karma : How to configure karma easilly ? In Poi v10 we can use the karma poi.config property. Now it seems not possible.
- bundle-report : Have you an update for poi v12 ?
- offline : Have you an update for poi v12 ?

**Comment by throrin19** [comment]
Ok, I add offline-plugin in POI with the `configureWebpack` entry. I add this inside the function And add my pwa.js in entry

```js
{
    entry : ['node_modules/@babel/polyfill', 'src/pwa.js', 'src/index.js'],
    configureWebpack(cfg) {
        // ...
        cfg.plugins.push(new OfflinePlugin({
            autoUpdate    : true,
            ServiceWorker : {
                events              : true,
                navigateFallbackURL : '/',
                minify              : true,
            },
            AppCache : {
                events      : true,
                FALLBACK    : { '/' : '/' },
            },
        }));

        return cfg;
    },
}
```

The sw.js is correctly generated but I have only one problem : It's not minified but I have the option set to `true`. Why ?

**Comment by egoist** [comment]
> 1. karma

somehow we need to make that plugin read `karma.config.js` and merge it with our default one, however can you elaborate the needs for custom configurations?

> 2. bundle-report

there're plenty of webpack plugins that can do this, I'm thinking about adding a default one since this feature can be useful for every app, still open to discussion.

> 3. offline

here's a [pwa](https://github.com/egoist/poi/tree/master/plugins/pwa) plugin which uses workbox-webpack-plugin.

for `offline-plugin` you need to set the `ServiceWorker.minify` option accordingly, i.e. `minify: process.env.NODE_ENV === 'production'`

**Comment by throrin19** [comment]
Thanks for your answers, 

For karma, the best is the same options as poi v10 version 👍 

For bundle-report, I try to make others poi plugins and test others webpack analysers and I propose them in pull request if my tests are fine

**Comment by egoist** [comment]
Just updated karma plugin which should work fine for most cases.

**Comment by throrin19** [comment]
thanks for karma but I've a problem. Only test files can't use Vue components works correctly. Others files are simply ignored by Karma. But it works correctly in POI v10
